buybackprogram/urls.py
from django.urls import path

from buybackprogram.views import calculate, common, programs, special_taxes, stats

app_name = "buybackprogram"

urlpatterns = [
    path("", common.index, name="index"),
    path("faq", common.faq, name="faq"),
    path("setup", programs.setup, name="setup"),
    path("program_add", programs.program_add, name="program_add"),
    path("location_add", programs.location_add, name="location_add"),
    path("user_settings_edit", common.user_settings_edit, name="user_settings_edit"),
    path(
        "location<int:location_pk>/remove",
        programs.location_remove,
        name="location_remove",
    ),
    path(
        "program/<int:program_pk>/leaderboard",
        stats.leaderboard,
        name="program_leaderboard",
    ),
    path(
        "program/<int:program_pk>/performance",
        stats.program_performance,
        name="program_performance",
    ),
    path(
        "program/<int:program_pk>/special_taxes",
        special_taxes.program_special_taxes,
        name="program_special_taxes",
    ),
    path(
        "program/<int:program_pk>/edit_item",
        special_taxes.program_edit_item,
        name="program_edit_item",
    ),
    path(
        "program/<int:program_pk>/edit_marketgroup",
        special_taxes.program_edit_marketgroup,
        name="program_edit_marketgroup",
    ),
    path(
        "program/<int:program_pk>/edit",
        programs.program_edit,
        name="program_edit",
    ),
    path(
        "program/<int:program_pk>/remove",
        programs.program_remove,
        name="program_remove",
    ),
    path(
        "program/<int:program_pk>/program_item/<int:item_pk>/remove",
        special_taxes.program_item_remove,
        name="program_item_remove",
    ),
    path(
        "program/<int:program_pk>/remove_all",
        special_taxes.program_item_remove_all,
        name="program_item_remove_all",
    ),
    path(
        "program/<int:program_pk>/calculate",
        calculate.program_calculate,
        name="program_calculate",
    ),
    path("my_stats", stats.my_stats, name="my_stats"),
    path(
        "tracking/<str:contract_title>/",
        stats.contract_details,
        name="contract_details",
    ),
    path("program_stats", stats.program_stats, name="program_stats"),
    path("program_stats_all", stats.program_stats_all, name="program_stats_all"),
    path(
        "item_autocomplete/",
        common.item_autocomplete,
        name="item_autocomplete",
    ),
    path(
        "solarsystem_autocomplete/",
        common.solarsystem_autocomplete,
        name="solarsystem_autocomplete",
    ),
    path(
        "marketgroup_autocomplete/",
        common.marketgroup_autocomplete,
        name="marketgroup_autocomplete",
    ),
]

buybackprogram/views/stats.py
import json
import os
from datetime import datetime

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.shortcuts import render
from django.utils import timezone
from eveuniverse.models import EveEntity

from allianceauth.authentication.models import CharacterOwnership
from allianceauth.services.hooks import get_extension_logger

from buybackprogram.app_settings import BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS
from buybackprogram.notes import (
    note_missing_from_contract,
    note_missing_from_tracking,
    note_quantity_missing_from_contract,
    note_quantity_missing_from_tracking,
)
from buybackprogram.utils import messages_plus

from ..models import (
    Contract,
    ContractItem,
    ContractNotification,
    Program,
    Tracking,
    TrackingItem,
)

logger = get_extension_logger(__name__)


@login_required
@permission_required("buybackprogram.basic_access")
def my_stats(request):
    # List for valid contracts to be displayed
    valid_contracts = []
    contract_notes = []

    # Tracker values
    values = {
        "outstanding": 0,
        "finished": 0,
        "outstanding_count": 0,
        "finished_count": 0,
    }

    # Request user owned characters
    characters = CharacterOwnership.objects.filter(user=request.user).values_list(
        "character__character_id", flat=True
    )

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(contract__isnull=False)
        .filter(contract__issuer_id__in=characters)
        .filter(contract__date_expired__gte=timezone.now())
        .prefetch_related("contract")
    )

    # Loop tracking objects to see if we have any contracts
    for tracking in tracking_numbers:
        # Get notes for this contract
        tracking.contract.notes = ContractNotification.objects.filter(
            contract=tracking.contract
        )

        # Walk the tracker values for contracts
        if tracking.contract.status == "outstanding":
            values["outstanding"] += tracking.contract.price
            values["outstanding_count"] += 1
        if tracking.contract.status == "finished":
            values["finished"] += tracking.contract.price
            values["finished_count"] += 1

        # Get the name for the issuer
        tracking.contract.issuer_name = EveEntity.objects.resolve_name(
            tracking.contract.issuer_id
        )

        # Get the name for the assignee
        tracking.contract.assignee_name = EveEntity.objects.resolve_name(
            tracking.contract.assignee_id
        )

        # Add contract to the valid contract list
        valid_contracts.append(tracking)
        contract_notes.append(tracking.contract.notes)

    context = {
        "contracts": valid_contracts,
        "contract_notes": contract_notes,
        "values": values,
        "mine": True,
    }

    return render(request, "buybackprogram/stats.html", context)


@login_required
@permission_required("buybackprogram.basic_access")
def leaderboard(request, program_pk):
    program = Program.objects.get(pk=program_pk)

    # Tracker values
    monthstats = {
        "users": {},  # monthly stats per user
        "userinfo": {},  # profile information per user
        "months": None,  # all months
    }
    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(program_id=program_pk)
        .filter(contract__isnull=False)
        .prefetch_related("contract")
    )

    # Loop all tracking objects
    for tracking in tracking_numbers:
        # For finished contracts, gather more data
        if tracking.contract.status == "finished":
            month = datetime.strftime(tracking.contract.date_issued, "%Y-%m:%B %Y")
            if month not in monthstats["users"]:
                monthstats["users"][month] = {}  # User data per month

            # Collect ISK data per user
            user = tracking.contract.issuer_id
            if user not in monthstats["users"][month]:
                monthstats["users"][month][user] = [
                    0,  # contract total
                    0,  # donation total
                ]
            monthstats["users"][month][user][0] += float(tracking.contract.price)
            monthstats["users"][month][user][1] += float(tracking.donation)

            if user not in monthstats["userinfo"]:
                monthstats["userinfo"][user] = {
                    "name": EveEntity.objects.resolve_name(user),
                    "pic": f"https://images.evetech.net/characters/{user}/portrait?size=32",
                }

    monthstats["months"] = sorted(list(monthstats["users"].keys()))
    context = {
        "stats": json.dumps(monthstats),
        "program": program,
    }

    return render(request, "buybackprogram/leaderboards.html", context)


@login_required
@permission_required("buybackprogram.manage_programs")
def program_performance(request, program_pk):
    static_path = os.path.join(settings.STATIC_ROOT, "buybackprogram/performance_data")
    filename = f"program_performance_{program_pk}.json"
    file_path = os.path.join(static_path, filename)

    try:
        # Try to open the file and load the JSON data
        with open(file_path, "r") as file:
            context = json.load(file)
    except FileNotFoundError:
        messages_plus.error(
            request,
            "Error: The performance data file is missing for this program. Please generate the report first.",
        )
        return render(
            request,
            "buybackprogram/performance.html",
        )

    return render(request, "buybackprogram/performance.html", context)


@login_required
@permission_required("buybackprogram.manage_programs")
def program_stats(request):
    # List for valid contracts to be displayed
    valid_contracts = []
    untracked_contracts = False

    # Tracker values
    values = {
        "outstanding": 0,
        "finished": 0,
        "outstanding_count": 0,
        "finished_count": 0,
        "untracked_count": 0,
    }

    # Request user owned characters
    characters = CharacterOwnership.objects.filter(user=request.user).values_list(
        "character__character_id", flat=True
    )

    # Request user owned corporations
    corporations = CharacterOwnership.objects.filter(user=request.user).values_list(
        "character__corporation_id", flat=True
    )

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(contract__isnull=False)
        .filter(
            Q(contract__assignee_id__in=characters)
            | Q(contract__assignee_id__in=corporations)
        )
        .filter(contract__date_expired__gte=timezone.now())
        .prefetch_related("contract")
    )

    # Loop tracking objects to see if we have any contracts
    for tracking in tracking_numbers:
        # Get notes for this contract
        tracking.contract.notes = ContractNotification.objects.filter(
            contract=tracking.contract
        )

        # Walk the tracker values for contracts
        if tracking.contract.status == "outstanding":
            values["outstanding"] += tracking.contract.price
            values["outstanding_count"] += 1
        if tracking.contract.status == "finished":
            values["finished"] += tracking.contract.price
            values["finished_count"] += 1

        # Get the name for the issuer
        tracking.contract.issuer_name = EveEntity.objects.resolve_name(
            tracking.contract.issuer_id
        )

        # Get the name for the assignee
        tracking.contract.assignee_name = EveEntity.objects.resolve_name(
            tracking.contract.assignee_id
        )

        # Add contract to the valid contract list
        valid_contracts.append(tracking)

    if BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS:
        # Get pending contracts that have no tracking assigned to them
        untracked_contracts = Contract.objects.filter(
            Q(assignee_id__in=characters) | Q(assignee_id__in=corporations)
        ).filter(no_tracking=True, status="outstanding")

        logger.debug("Got %s untracked contracts" % len(untracked_contracts))

        for contract in untracked_contracts:
            values["untracked_count"] += 1

            # Get notes for this contract
            contract.notes = ContractNotification.objects.filter(contract=contract)

            # Get the name for the issuer
            contract.issuer_name = EveEntity.objects.resolve_name(contract.issuer_id)

            # Get the name for the assignee
            contract.assignee_name = EveEntity.objects.resolve_name(
                contract.assignee_id
            )

    context = {
        "contracts": valid_contracts,
        "untracked_contracts": untracked_contracts,
        "values": values,
        "mine": True,
        "BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS": BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS,
    }

    return render(request, "buybackprogram/stats.html", context)


@login_required
@permission_required("buybackprogram.see_all_statics")
def program_stats_all(request):
    # List for valid contracts to be displayed
    valid_contracts = []

    untracked_contracts = False

    # Tracker values
    values = {
        "outstanding": 0,
        "finished": 0,
        "outstanding_count": 0,
        "finished_count": 0,
        "untracked_count": 0,
    }

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(contract__isnull=False)
        .filter(contract__date_expired__gte=timezone.now())
        .prefetch_related("contract")
    )

    # Loop tracking objects to see if we have any contracts
    for tracking in tracking_numbers:

buybackprogram/templates/buybackprogram/partials/stats/tabs/finished.html
{% load i18n %}
{% load humanize %}
{% load price_formats %}

<div id="tab-finished" class="tab-pane fade card card-default border-0" role="tabpanel" aria-labelledby="tab-finished">
    <div class="card-body">
        <table class="table table-striped table-hover no-footer w-100" id="dashboard-recent-fatlinks">
            <thead>
                <tr>
                    <th >{% trans "Issuer" %}</th>
                    <th >{% trans "Assignee" %}</th>
                    <th >{% trans "Location" %}</th>
                    <th >{% trans "Date issued" %}</th>
                    <th >{% trans "Time pending" %}</th>
                    <th >{% trans "Status" %}</th>
                    <th >{% trans "Tracking #" %}</th>
                    <th >{% trans "Price" %}</th>
                    <th>{% trans "Notes" %}</th>
                    <th>{% trans "Action" %}</th>
                </tr>
            </thead>

            <tbody>
                {% for tracking in contracts %}
                    {% if tracking.contract.status == 'finished' %}
                        <tr>
                            <td>{{tracking.contract.issuer_name}}</td>
                            <td>{{tracking.contract.assignee_name}}</td>
                            <td>{{tracking.contract.location_name}}</td>
                            <td>{{tracking.contract.date_issued}}</td>
                            <td>{{tracking.contract.date_issued|timesince }}</td>
                            <td>{{tracking.contract.status}}</td>
                            <td>{{tracking.tracking_number}}</td>
                            <td>{{tracking.contract.price|custom_number_format:2|price}}</td>

                            <td>
                                {% for note in tracking.contract.notes %}
                                    <i style="color: {{note.color}};" class="fas {{note.icon}}" title="{{note.message}}"></i>
                                                {% endfor %}
                            </td>

                            <td><a class="btn btn-info btn-sm" href="{% url 'buybackprogram:contract_details' contract_title=tracking.tracking_number %}">
                                            {% translate "Details" %}</a></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>

            <tfoot>
            </tfoot>
        </table>
    </div>
</div>

buybackprogram/templates/buybackprogram/partials/stats/tabs/outstanding.html
{% load i18n %}
{% load humanize %}
{% load price_formats %}

<div id="tab-outstanding" class="tab-pane fade card card-default border-0 show active" role="tabpanel" aria-labelledby="tab-outstanding">
    <div class="card-body">
        <table class="table table-striped table-hover no-footer w-100">
            <thead>
                <tr>
                    <th >{% trans "Issuer" %}</th>
                    <th >{% trans "Assignee" %}</th>
                    <th >{% trans "Location" %}</th>
                    <th >{% trans "Date issued" %}</th>
                    <th >{% trans "Time pending" %}</th>
                    <th >{% trans "Status" %}</th>
                    <th >{% trans "Tracking #" %}</th>
                    <th >{% trans "Price" %}</th>
                    <th>{% trans "Notes" %}</th>
                    <th>{% trans "Action" %}</th>
                </tr>
            </thead>

            <tbody>
                {% for tracking in contracts %}
                    {% if tracking.contract.status == 'outstanding' %}
                        <tr>
                            <td>{{tracking.contract.issuer_name}}</td>
                            <td>{{tracking.contract.assignee_name}}</td>
                            <td>{{tracking.contract.location_name}}</td>
                            <td>{{tracking.contract.date_issued}}</td>
                            <td>{{tracking.contract.date_issued|timesince }}</td>
                            <td>{{tracking.contract.status}}</td>
                            <td>{{tracking.tracking_number}}</td>
                            <td>{{tracking.contract.price|custom_number_format:2|price}}</td>

                            <td>
                                {% for note in tracking.contract.notes %}
                                    <i style="color: {{note.color}};" class="fas {{note.icon}}" title="{{note.message}}"></i>
                                                {% endfor %}
                            </td>

                            <td><a class="btn btn-info btn-sm" href="{% url 'buybackprogram:contract_details' contract_title=tracking.tracking_number %}">
                                            {% trans "Details" %}</a></td>
                        </tr>
                    {% endif %}
                {% endfor %}
            </tbody>

            <tfoot>
            </tfoot>
        </table>
    </div>
</div>

buybackprogram/templates/buybackprogram/partials/stats/tabs/tabs-navigation.html
{% load i18n %}
<ul class="nav nav-tabs">
    <li class="nav-item" role="presentation">
        <a
            class="nav-link active"
            id="outstanding"
            data-bs-toggle="tab"
            href="#tab-outstanding"
            role="tab"
            aria-controls="home"
            aria-selected="true"
        >
            {% trans "Outstanding" %} ({{values.outstanding_count}})
        </a>
    </li>

    <li>
        <a
            class="nav-link"
            id="finished"
            data-bs-toggle="tab"
            href="#tab-finished"
            role="tab"
            aria-controls="home"
            aria-selected="false"
        >
            {% trans "Finished" %} ({{values.finished_count}})
        </a>
    </li>
    <li>
        <a
            class="nav-link"
            id="untracked"
            data-bs-toggle="tab"
            href="#tab-untracked"
            role="tab"
            aria-controls="home"
            aria-selected="false"
        >
            {% trans "Untracked" %} ({{values.untracked_count}})
        </a>
    </li>
</ul>

buybackprogram/templates/buybackprogram/partials/stats/tabs/untracked.html
{% load i18n %}
{% load humanize %}
{% load price_formats %}

<div id="tab-untracked" class="tab-pane fade card card-default border-0" role="tabpanel" aria-labelledby="tab-untracked">
    <div class="card-body">
        <table class="table table-striped table-hover no-footer w-100" id="dashboard-recent-fatlinks">
            <thead>
                <tr>
                    <th >{% trans "Issuer" %}</th>
                    <th >{% trans "Assignee" %}</th>
                    <th >{% trans "Location" %}</th>
                    <th >{% trans "Date issued" %}</th>
                    <th >{% trans "Time pending" %}</th>
                    <th >{% trans "Status" %}</th>
                    <th >{% trans "Tracking #" %}</th>
                    <th >{% trans "Price" %}</th>
                    <th>{% trans "Notes" %}</th>
                    <th>{% trans "Action" %}</th>
                </tr>
            </thead>

            <tbody>
                {% if BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS %}
                    {% for contract in untracked_contracts %}
                        {% if contract.status == 'outstanding' %}
                            <tr>
                                <td>{{contract.issuer_name}}</td>
                                <td>{{contract.assignee_name}}</td>
                                <td>{{contract.location_name}}</td>
                                <td>{{contract.date_issued}}</td>
                                <td>{{contract.date_issued|timesince }}</td>
                                <td>{{contract.status}}</td>
                                <td>{{contract.title}}</td>
                                <td>{{contract.price|custom_number_format:2|price}}</td>

                                <td colspan="2">
                                    {% for note in contract.notes %}
                                    <i style="color: {{note.color}};" class="fas {{note.icon}}" title="{{note.message}}"></i>
                                    {% endfor %}
                                </td>


                            </tr>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </tbody>

            <tfoot>
            </tfoot>
        </table>
    </div>
</div>
<thead>