buybackprogram/urls.py
from django.urls import path

from buybackprogram.views import calculate, common, programs, special_taxes, stats

app_name = "buybackprogram"

urlpatterns = [
    path("", common.index, name="index"),
    path("faq", common.faq, name="faq"),
    path("setup", programs.setup, name="setup"),
    path("program_add", programs.program_add, name="program_add"),
    path("location_add", programs.location_add, name="location_add"),
    path("user_settings_edit", common.user_settings_edit, name="user_settings_edit"),
    path(
        "location<int:location_pk>/remove",
        programs.location_remove,
        name="location_remove",
    ),
    path(
        "program/<int:program_pk>/leaderboard",
        stats.leaderboard,
        name="program_leaderboard",
    ),
    path(
        "program/<int:program_pk>/performance",
        stats.program_performance,
        name="program_performance",
    ),
    path(
        "program/<int:program_pk>/special_taxes",
        special_taxes.program_special_taxes,
        name="program_special_taxes",
    ),
    path(
        "program/<int:program_pk>/edit_item",
        special_taxes.program_edit_item,
        name="program_edit_item",
    ),
    path(
        "program/<int:program_pk>/edit_marketgroup",
        special_taxes.program_edit_marketgroup,
        name="program_edit_marketgroup",
    ),
    path(
        "program/<int:program_pk>/edit",
        programs.program_edit,
        name="program_edit",
    ),
    path(
        "program/<int:program_pk>/remove",
        programs.program_remove,
        name="program_remove",
    ),
    path(
        "program/<int:program_pk>/program_item/<int:item_pk>/remove",
        special_taxes.program_item_remove,
        name="program_item_remove",
    ),
    path(
        "program/<int:program_pk>/remove_all",
        special_taxes.program_item_remove_all,
        name="program_item_remove_all",
    ),
    path(
        "program/<int:program_pk>/calculate",
        calculate.program_calculate,
        name="program_calculate",
    ),
    path("my_stats", stats.my_stats, name="my_stats"),
    path(
        "tracking/<str:contract_title>/",
        stats.contract_details,
        name="contract_details",
    ),
    path("program_stats", stats.program_stats, name="program_stats"),
    path("program_stats_all", stats.program_stats_all, name="program_stats_all"),
    path(
        "item_autocomplete/",
        common.item_autocomplete,
        name="item_autocomplete",
    ),
    path(
        "solarsystem_autocomplete/",
        common.solarsystem_autocomplete,
        name="solarsystem_autocomplete",
    ),
    path(
        "marketgroup_autocomplete/",
        common.marketgroup_autocomplete,
        name="marketgroup_autocomplete",
    ),
]

buybackprogram/views/stats.py
import json
import os
from datetime import datetime

from django.conf import settings
from django.contrib.auth.decorators import login_required, permission_required
from django.db.models import Q
from django.shortcuts import render
from django.utils import timezone
from eveuniverse.models import EveEntity

from allianceauth.authentication.models import CharacterOwnership
from allianceauth.services.hooks import get_extension_logger

from buybackprogram.app_settings import BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS
from buybackprogram.notes import (
    note_missing_from_contract,
    note_missing_from_tracking,
    note_quantity_missing_from_contract,
    note_quantity_missing_from_tracking,
)
from buybackprogram.utils import messages_plus

from ..models import (
    Contract,
    ContractItem,
    ContractNotification,
    Program,
    Tracking,
    TrackingItem,
)

logger = get_extension_logger(__name__)


@login_required
@permission_required("buybackprogram.basic_access")
def my_stats(request):
    # List for valid contracts to be displayed
    valid_contracts = []
    contract_notes = []

    # Tracker values
    values = {
        "outstanding": 0,
        "finished": 0,
        "outstanding_count": 0,
        "finished_count": 0,
    }

    # Request user owned characters
    characters = CharacterOwnership.objects.filter(user=request.user).values_list(
        "character__character_id", flat=True
    )

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(contract__isnull=False)
        .filter(contract__issuer_id__in=characters)
        .filter(contract__date_expired__gte=timezone.now())
        .prefetch_related("contract")
    )

    # Loop tracking objects to see if we have any contracts
    for tracking in tracking_numbers:
        # Get notes for this contract
        tracking.contract.notes = ContractNotification.objects.filter(
            contract=tracking.contract
        )

        # Walk the tracker values for contracts
        if tracking.contract.status == "outstanding":
            values["outstanding"] += tracking.contract.price
            values["outstanding_count"] += 1
        if tracking.contract.status == "finished":
            values["finished"] += tracking.contract.price
            values["finished_count"] += 1

        # Get the name for the issuer
        tracking.contract.issuer_name = EveEntity.objects.resolve_name(
            tracking.contract.issuer_id
        )

        # Get the name for the assignee
        tracking.contract.assignee_name = EveEntity.objects.resolve_name(
            tracking.contract.assignee_id
        )

        # Add contract to the valid contract list
        valid_contracts.append(tracking)
        contract_notes.append(tracking.contract.notes)

    context = {
        "contracts": valid_contracts,
        "contract_notes": contract_notes,
        "values": values,
        "mine": True,
    }

    return render(request, "buybackprogram/stats.html", context)


@login_required
@permission_required("buybackprogram.basic_access")
def leaderboard(request, program_pk):
    program = Program.objects.get(pk=program_pk)

    # Tracker values
    monthstats = {
        "users": {},  # monthly stats per user
        "userinfo": {},  # profile information per user
        "months": None,  # all months
    }
    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(program_id=program_pk)
        .filter(contract__isnull=False)
        .prefetch_related("contract")
    )

    # Loop all tracking objects
    for tracking in tracking_numbers:
        # For finished contracts, gather more data
        if tracking.contract.status == "finished":
            month = datetime.strftime(tracking.contract.date_issued, "%Y-%m:%B %Y")
            if month not in monthstats["users"]:
                monthstats["users"][month] = {}  # User data per month

            # Collect ISK data per user
            user = tracking.contract.issuer_id
            if user not in monthstats["users"][month]:
                monthstats["users"][month][user] = [
                    0,  # contract total
                    0,  # donation total
                ]
            monthstats["users"][month][user][0] += float(tracking.contract.price)
            monthstats["users"][month][user][1] += float(tracking.donation)

            if user not in monthstats["userinfo"]:
                monthstats["userinfo"][user] = {
                    "name": EveEntity.objects.resolve_name(user),
                    "pic": f"https://images.evetech.net/characters/{user}/portrait?size=32",
                }

    monthstats["months"] = sorted(list(monthstats["users"].keys()))
    context = {
        "stats": json.dumps(monthstats),
        "program": program,
    }

    return render(request, "buybackprogram/leaderboards.html", context)


@login_required
@permission_required("buybackprogram.manage_programs")
def program_performance(request, program_pk):
    static_path = os.path.join(settings.STATIC_ROOT, "buybackprogram/performance_data")
    filename = f"program_performance_{program_pk}.json"
    file_path = os.path.join(static_path, filename)

    try:
        # Try to open the file and load the JSON data
        with open(file_path, "r") as file:
            context = json.load(file)
    except FileNotFoundError:
        messages_plus.error(
            request,
            "Error: The performance data file is missing for this program. Please generate the report first.",
        )
        return render(
            request,
            "buybackprogram/performance.html",
        )

    return render(request, "buybackprogram/performance.html", context)


@login_required
@permission_required("buybackprogram.manage_programs")
def program_stats(request):
    # List for valid contracts to be displayed
    valid_contracts = []
    untracked_contracts = False

    # Tracker values
    values = {
        "outstanding": 0,
        "finished": 0,
        "outstanding_count": 0,
        "finished_count": 0,
        "untracked_count": 0,
    }

    # Request user owned characters
    characters = CharacterOwnership.objects.filter(user=request.user).values_list(
        "character__character_id", flat=True
    )

    # Request user owned corporations
    corporations = CharacterOwnership.objects.filter(user=request.user).values_list(
        "character__corporation_id", flat=True
    )

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(contract__isnull=False)
        .filter(
            Q(contract__assignee_id__in=characters)
            | Q(contract__assignee_id__in=corporations)
        )
        .filter(contract__date_expired__gte=timezone.now())
        .prefetch_related("contract")
    )

    # Loop tracking objects to see if we have any contracts
    for tracking in tracking_numbers:
        # Get notes for this contract
        tracking.contract.notes = ContractNotification.objects.filter(
            contract=tracking.contract
        )

        # Walk the tracker values for contracts
        if tracking.contract.status == "outstanding":
            values["outstanding"] += tracking.contract.price
            values["outstanding_count"] += 1
        if tracking.contract.status == "finished":
            values["finished"] += tracking.contract.price
            values["finished_count"] += 1

        # Get the name for the issuer
        tracking.contract.issuer_name = EveEntity.objects.resolve_name(
            tracking.contract.issuer_id
        )

        # Get the name for the assignee
        tracking.contract.assignee_name = EveEntity.objects.resolve_name(
            tracking.contract.assignee_id
        )

        # Add contract to the valid contract list
        valid_contracts.append(tracking)

    if BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS:
        # Get pending contracts that have no tracking assigned to them
        untracked_contracts = Contract.objects.filter(
            Q(assignee_id__in=characters) | Q(assignee_id__in=corporations)
        ).filter(no_tracking=True, status="outstanding")

        logger.debug("Got %s untracked contracts" % len(untracked_contracts))

        for contract in untracked_contracts:
            values["untracked_count"] += 1

            # Get notes for this contract
            contract.notes = ContractNotification.objects.filter(contract=contract)

            # Get the name for the issuer
            contract.issuer_name = EveEntity.objects.resolve_name(contract.issuer_id)

            # Get the name for the assignee
            contract.assignee_name = EveEntity.objects.resolve_name(
                contract.assignee_id
            )

    context = {
        "contracts": valid_contracts,
        "untracked_contracts": untracked_contracts,
        "values": values,
        "mine": True,
        "BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS": BUYBACKPROGRAM_TRACK_PREFILL_CONTRACTS,
    }

    return render(request, "buybackprogram/stats.html", context)


@login_required
@permission_required("buybackprogram.see_all_statics")
def program_stats_all(request):
    # List for valid contracts to be displayed
    valid_contracts = []

    untracked_contracts = False

    # Tracker values
    values = {
        "outstanding": 0,
        "finished": 0,
        "outstanding_count": 0,
        "finished_count": 0,
        "untracked_count": 0,
    }

    # Get all tracking objects that have a linked contract to them for the user
    tracking_numbers = (
        Tracking.objects.filter(contract__isnull=False)
        .filter(contract__date_expired__gte=timezone.now())
        .prefetch_related("contract")
    )

    # Loop tracking objects to see if we have any contracts
    for tracking in tracking_numbers:

buybackprogram/templates/buybackprogram/contract_details.html
{% extends 'buybackprogram/base.html' %}
{% load i18n %}
{% load humanize %}
{% load price_formats %}
{% load static %}
{% block details %}

<div class="panel-body" style="min-height: 100px;">
    <div class="row row-cols-1 row-cols-md-2 g-4">
        <div class="col">
            <div class="card">
                <div class="card-header">{% trans "Contract Information" %}</div>
                <div class="card-body">
                    {% include "buybackprogram/partials/details/contract-info.html" %}
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card">
                <div class="card-header">{% trans "Contract Notes" %}
                <div class="card-body">
                    {% include "buybackprogram/partials/details/warning.html" %}
                </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card" style="margin-top:10px">
        <div class="card-header">{% trans "Accepted Location(s)" %}</div>
        <div class="card-body">
            {% include "buybackprogram/partials/details/accepted-locations.html" %}
        </div>
    </div>

    <div class="card" style="margin-top:10px">
        <div class="card-header">{% trans "Invoice" %}</div>
        <div class="card-body">
            {% include "buybackprogram/partials/details/invoice.html" %}
        </div>
    </div>

    <div class="card" style="margin-top:10px">
        <div class="card-header">{% trans "Contract items" %}</div>
        <div class="card-body">
            <!-- Nav tabs -->
            {% include "buybackprogram/partials/details/tabs/tabs-navigation.html" %}

            <div class="tab-content" id="nav-tabContent">
                {% include "buybackprogram/partials/details/tabs/contract-items.html" %}
                {% include "buybackprogram/partials/details/tabs/original-items.html" %}
            </div>
        </div>
    </div>

    <div>
        <a class="btn btn-warning btn-sm" href="{% url 'buybackprogram:my_stats' %}">
                                <i class="fas fa-arrow-left"></i> {% trans "Back to my stats" %}
        </a>
    </div>
</div>
{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_css %}
{% if NIGHT_MODE %}
        <link rel="stylesheet" type="text/css" href="{% static 'buybackprogram/css/style_dark.css' %}">
        {% else %}
        <link rel="stylesheet" type="text/css" href="{% static 'buybackprogram/css/style_light.css' %}">
    {% endif %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/index.html
{% extends 'buybackprogram/base.html' %}
{% load i18n %}
{% load humanize %}
{% load static %}
{% load program_settings %}

{% block extra_css %}

{% include "buybackprogram/bundles/buybackprogram-css-light.html" %}

{% endblock extra_css %}

{% block details %}

<div class="card">
    <div class="card-header">
        {% trans "Buyback Programs" %}
    </div>
    <table style="width: 100%; margin: auto;" class="table table-striped table-hover no-footer w-100">
        <thead>
            <tr>
                <th>{% trans "Name" %}</th>
                <th>{% trans "Location(s)" %}</th>
                <th>{% trans "Tax" %}</th>
                <th>{% trans "Manager" %}</th>
                <th>{% trans "Settings" %}</th>
                <th class="text-center" >{% trans "Actions" %}</th>
            </tr>
        </thead>
        <tbody>
            {% for program in programs %}
            <tr>
                <td>{{ program.name }} </td>

                <td>
                {% for location in program.location.all %}
                    <div>{{location.location_display_name}}</div>
                {% endfor %}
                </td>

                <td>{{ program.tax }} %</td>

                {% if program.is_corporation %}
                    <td >{{ program.owner.corporation }}</td>
                {% else %}
                    <td >{{ program.owner.character.character }}</td>
                {% endif %}
                <td>
                    {% for setting in program|program_setting %}
                        <i style="color: {{setting.color}};" class="fas {{setting.icon}}" title="{{setting.message}}"></i>
                    {% endfor %}

                </td>


                <td class="text-center">
                    <a class="btn btn-success btn-sm" href="{% url 'buybackprogram:program_calculate' program_pk=program.id %}">
                        {% trans "Use" %}
                    </a>

                    {% if perms.buybackprogram.see_leaderboard %}
                        <a class="btn btn-sm btn-info" href="{% url 'buybackprogram:program_leaderboard' program_pk=program.id %}">{% trans "Leaderboard" %}</a>
                    {% endif %}

                    {% if program.owner.user == request.user or perms.buybackprogram.see_performance %}
                        <a class="btn btn-sm btn-info" href="{% url 'buybackprogram:program_performance' program_pk=program.id %}">{% trans "Performance" %}</a>
                    {% endif %}

                    <a class="btn btn-sm btn-warning" href="{% url 'buybackprogram:program_special_taxes' program_pk=program.id %}">{% trans "Special taxes" %}</a>

                    {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
                        <a class="btn btn-sm btn-warning" href="{% url 'buybackprogram:program_edit' program_pk=program.id %}">{% trans "Edit program" %}</a>
                        <a class="btn btn-danger btn-sm" href="{% url 'buybackprogram:program_remove' program_pk=program.id %}">
                        {% trans "Delete" %}
                    </a>
                    {% endif %}

                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>


{% endblock %}

{% block extra_javascript %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/location_add.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="card">
  <div class="card-body">
      <form class="form" action="{% url 'buybackprogram:location_add' %}" method="POST">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-primary">{% trans "Add location" %}</button>
      </form>
      <table id="locations" style="margin: 20px auto;" class="table table-striped table-condensed">
      <thead>
        <th>{% trans "Solar System" %}</th>
        <th style="text-align: center;">{% trans "Name" %}</th>
        <th style="text-align: center;">{% trans "Structure ID" %}</th>
      </thead>
      <tbody>
        {% for location in locations %}
          {% if location.owner.user == request.user %}
            <tr>
              <td>{{location.eve_solar_system.name}}</td>
              <td style="text-align: center;">{{location.name}}</td>
              <td style="text-align: center;">{{location.structure_id}}</td>
              <td><a class="btn btn-sm btn-danger" href="{% url 'buybackprogram:location_remove' location_pk=location.id %}">{% trans "Delete" %}</a></td>
            </tr>
          {% endif %}
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% include "buybackprogram/bundles/buybackprogram-css-light.html" %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/program_calculate.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}
{% load price_formats %}
{% load help_icons %}

{% block body %}


{% if buyback_data %}
<div class="card text-white bg-success">
  <div class="card-header">{% trans "Calculation Succesfull" %}</div>
  <div class="card-body">
    {% include "buybackprogram/partials/calculate/calculation_success.html" %}
  </div>
</div>

<div class="card" style="margin-top:10px;">
  <div class="card-header"><h5>{% trans "Accepted location(s)" %} <i class="fas fa-light fa-question" title="{% help 'accepted_locations' %}"></i></h5></div>
  <div class="card-body">
    {% include "buybackprogram/partials/calculate/accepted_locations.html" %}
  </div>
</div>

<div class="card" style="margin-top:10px;">
  <div class="card-header"><h5>{% trans "Contact Settings" %} <i class="fas fa-light fa-question" title="{% help 'contract_settings' %}"></i></h5></div>
  <div class="card-body">
    {% include "buybackprogram/partials/calculate/contract_settings.html" %}
  </div>
</div>

<div class="card" style="margin-top:10px;">
  <div class="card-header"><h5>{% trans "Invoice" %} <i class="fas fa-light fa-question" title="{% help 'invoice' %}"></i></h5></div>
  <div class="card-body">
    {% include "buybackprogram/partials/calculate/invoice.html" %}
  </div>
</div>

<div class="card" style="margin-top:10px;">
  <div class="card-header"><h5>{% trans "Item Details" %} <i class="fas fa-light fa-question" title="{% help 'item_details' %}"></i></h5></div>
  <div class="card-body">
    {% include "buybackprogram/partials/calculate/item_details.html" %}
  </div>
</div>
    {% endif %}

<div class="card" style="margin-top:10px;">
    <h5 class="card-header">{% trans "Contract calculator" %}</h5>
    <div class="card-body">
        <form class="form" action="{% url 'buybackprogram:program_calculate' program_pk=program.id %}" method="POST">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button type="submit" class="btn btn-primary">{% trans "Calculate" %}</button>
            </form>
    </div>
    <div class="card-footer text-muted" >
        <b>{% trans "Selected Program:" %} </b>{% if program.name %}{{program.name}},{% endif %} managed by {% if program.is_corporation %}{{ program.owner.corporation }}{% else %}{{ program.owner.character.character }}{% endif %}
    </div>
</div>

{% endblock %}

{% block extra_javascript %}
<script>
document.querySelectorAll('button[data-type="copy"]')
  .forEach(function(button){
      button.addEventListener('click', function(){
      let email = this.parentNode.parentNode
        .querySelector('td[data-type="copy_value"]')
        .innerText;

      let tmp = document.createElement('textarea');
          tmp.value = email;
          tmp.setAttribute('readonly', '');
          tmp.style.position = 'absolute';
          tmp.style.left = '-9999px';
          document.body.appendChild(tmp);
          tmp.select();
          document.execCommand('copy');
          document.body.removeChild(tmp);
          console.log(`${email} copied.`);
    });
});
</script>
{% endblock %}

{% block extra_css %}
{% include "buybackprogram/bundles/buybackprogram-css-light.html" %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/program_edit_item.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="card">
  <h5 class="card-header">{% trans "Add Special Item Tax to Program" %}</h5>
  <div class="card-body">
    {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
      <form class="form" action="{% url 'buybackprogram:program_edit_item' program_pk=program.id %}" method="POST">
        {% csrf_token %}
        {{ form|bootstrap }}
        <button type="submit" class="btn btn-primary">{% trans "Add item" %}</button>
      </form>
    {% endif %}
  </div>
  <div class="card-footer text-muted">
    <a class="btn btn-default navbar-btn btn-warning" href="{% url 'buybackprogram:program_special_taxes' program_pk=program.id %}"><i class="fas fa-long-arrow-alt-left"></i> {% trans "Back to item taxes" %}</a>
  </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% include "buybackprogram/bundles/buybackprogram-css-light.html" %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/program_edit_marketgroup.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="card">
  <h5 class="card-header">{% trans "Add Special Marketgroup Tax to Program" %}</h5>
  <div class="card-body">
    {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
      <form class="form" action="{% url 'buybackprogram:program_edit_marketgroup' program_pk=program.id %}" method="POST">
      {% csrf_token %}
      {{ form|bootstrap }}
      <button type="submit" class="btn btn-primary">{% trans "Add market group" %}</button>
    </form>
    {% endif %}
  </div>
  <div class="card-footer text-muted">
    <a class="btn btn-default navbar-btn btn-warning" href="{% url 'buybackprogram:program_special_taxes' program_pk=program.id %}"><i class="fas fa-long-arrow-alt-left"></i> {% trans "Back to item taxes" %}</a>
  </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% include "buybackprogram/bundles/buybackprogram-css-light.html" %}
{% endblock %}

{% block extra_script %}
{% endblock %}

buybackprogram/templates/buybackprogram/program_special_taxes.html
{% extends 'buybackprogram/page.html' %}
{% load i18n %}
{% load humanize %}
{% load bootstrap %}
{% load static %}

{% block body %}
<div class="card">
  <div class="card-header">
    {% trans "Program Special Taxes" %}
  </div>
  <div class="card-body">
    {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
    <a class="btn btn-sm btn-warning" href="{% url 'buybackprogram:program_edit_item' program_pk=program.id %}"><i class="fas fa-plus"></i> {% trans "Add item" %}</a>
    <a class="btn btn-sm btn-warning" href="{% url 'buybackprogram:program_edit_marketgroup' program_pk=program.id %}"><i class="fas fa-plus"></i> {% trans "Add market group" %}</a>
    <a class="btn btn-sm btn-danger" href="{% url 'buybackprogram:program_item_remove_all' program_pk=program.id %}"><i class="fas fa-trash"></i> {% trans "Deleta all items" %}</a>
  {% endif %}
    <p style="margin-top:5px;">{% trans "This section shows all special item taxes applied to this program. Taxes may either be additional taxes or discounts." %}</p>
    <table id="program_items" class="table table-striped table-hover no-footer w-100">
      <thead>
        <th>Name</th>
        <th style="text-align: center;">{% trans "Tax adjustment" %}</th>
        <th style="text-align: center;">{% trans "Total tax" %}</th>
        <th style="text-align: center;">{% trans "Is allowed" %}</th>
        {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
          <th style="text-align: center;">{% trans "Actions" %}</th>
        {% endif %}
      </thead>
      <tbody>
        {% for item in program_items %}
          <tr>
            <td>{{item.item_type.name}}</td>
            <td style="text-align: center;">{{item.item_tax}} %</td>
            <td style="text-align: center;">{{item.item_tax|add:program.tax }} %</td>
            {% if not item.disallow_item %}
               <td style="text-align: center;"><i class="fas fa-check" style="color:green;"></i></td>
            {% else %}
              <td style="text-align: center;"><i class="fas fa-times" style="color:red;"></i></td>
            {% endif %}
            {% if perms.buybackprogram.manage_programs and program.owner.user == request.user %}
              <td style="text-align: center;">
                <a class="btn btn-danger btn-sm" href="{% url 'buybackprogram:program_item_remove' item_pk=item.item_type.id program_pk=program.id %}">Delete</a>

              </td>
            {% endif %}
          </tr>
        {% endfor %}
      </tbody>
    </table>

  </div>
</div>
{% endblock %}

{% block extra_javascript %}
<script type="text/javascript" src="{% static 'buybackprogram/js/bootstrap-autocomplete.min.js' %}"></script>
<script type="text/javascript" src="{% static 'buybackprogram/js/autocomplete.js' %}"></script>
{% endblock %}

{% block extra_css %}
{% include "buybackprogram/bundles/buybackprogram-css-light.html" %}
{% endblock %}

{% block extra_script %}
{% endblock %}